export const invalidNames = [
  'month_start',
  'week_day',
  'week_start',
  'year',
  'date',
  'hour',
  'minute',
  'month_start',
  'second',
  'week_day',
  'week_start',
  'year'
];

export const validNames = {
  'count': 'Количество',
  'day': 'День',
  'is_null': 'Пустое значение',
  'iso_week': 'Неделя',
  'iso_year': 'Год',
  'max': 'Максимальное значение',
  'min': 'Минимальное значение',
  'month': 'Месяц',
  'average': 'Среднее значение',
  'sum': 'Сумма',
  'quarter': 'Квартал',
  'auth.Group': 'группы',
  'n3calendar.ProductionCalendarDay': 'Производственные календарные дни',
  'oks.OKS': 'Объекты капитального строительства',
  'oks.OKSPassportFileLog': 'Логи изменения паспортов ОКС',
  'oks.Expertise': 'Экспертизы УГЭ',
  'oks.OKSWorkStage': 'Этапы работ по ОКС',
  'oks.OKSWorkPhase': 'Стадии работ по ОКС',
  'oks.ConstructiveType': 'Виды конструкций',
  'oks.OKSPassportActualization': 'Актуализация паспортов ОКС',
  'oks.OKSPhoto': 'Фото ОКС',
  'oks.OKSVideo': 'Видео ОКС',
  'oks.EstimatedCostReliabilityConclusion': 'Заключения о достоверности определения сметной стоимости',
  'oks.OKSHousing': 'Корпусы',
  'oks.OKSProblemQuestion': 'Проблемные вопросы',
  'oks.StateCase': 'Состояние дел',
  'oks.OKSWarranty': 'Гарантийные обязательства по ОКС',
  'orders.Offer': 'Предложения о включении ОКС в АИП',
  'orders.Order': 'Заявки отраслевых комитетов',
  'orders.OrderDocType': 'Типы документов заявки отраслевых комитетов',
  'orders.OrderReturnReason': 'Причины возвращения заявки отраслевых комитетов',
  'orders.OrderAdministration': 'Заявки администраций районов',
  'orders.OrderAdministrationReturnReason': 'Причины возвращения заявки администраций районов',
  'orders.OfferDoc': 'Документы заявки администраций районов',
  'organizations.Organization': 'Организации',
  'organizations.OrganizationalUnit': 'Организационные подразделения',
  'organizations.Sector': 'Отрасли',
  'organizations.Position': 'Должности',
  'users.User': 'пользователи',
  'users.OrganizationUnitRole': 'Роли отделов',
  'aip.OKSAIPEventPrice': 'Суммы ОКС в мероприятиях АИП',
  'aip.AdjustmentOKSAIPEventPrice': 'Суммы ОКС по мероприятиям АИП в корректировках АИП',
  'aip.AIPAdjustment': 'Корректировки АИП',
  'aip.AdjustmentOKSAIPEvent': 'Списки ОКС в мероприятиях АИП в корректировке АИП',
  'aip.OKSAIPEvent': 'Списки ОКС в мероприятиях АИП',
  'aip.AIPCast': 'Слепки АИП',
  'aip.CastOKSAIPEvent': 'Списки ОКС в мероприятиях АИП в слепках АИП',
  'aip.Aip': 'Адресные инвестиционные программы',
  'aip.EventsAip': 'Мероприятия АИП',
  'aip.EventIncludeAip': 'Включенные мероприятия АИП',
  'aip.AdjustmentIncludedEvent': 'Включенные мероприятия АИП в корректировках АИП',
  'aip.CastIncludedEvent': 'Слепки включенных мероприятий АИП',
  'aip.CheckDigits': 'Контрольные цифры',
  'aip.OKSContentProtocolMvk': 'ОКСы в строках протоколов МВК',
  'aip.ResponsibleForExecution': 'Ответственные за исполнения',
  'aip.ProtocolMvk': 'Протоколы МВК',
  'aip.ContentsProtocolMvk': 'Строки протоколов МВК',
  'aip.CostEventsAipProtocolMvk': 'Суммы по мероприятиям АИП в протоколе МВК',
  'gp.EventsGP': 'Мероприятия государственной программы',
  'gp.EventIncludeGP': 'Включенные мероприятия ГП',
  'gp.GP': 'Государственные программы',
  'gp.SubGP': 'Подпрограммы государственной программы',
  'gp.StageGP': 'Этапы строительства мероприятия ГП',
  'gp.CostStage': 'Суммы по этапу мероприятия ГП',
  'gp.SourceFinance': 'Источники финансирования',
  'gp.StageOKS': 'Списки ОКС в этапе мероприятия ГП',
  'gp.GPProjectChange': 'Предложения о внесения изменений в ГП',
  'gp.Adjustment': 'Корректировки ГП',
  'gp.TargetedItems': 'целевые статьи расходов',
  'gp.RealizationSchedule': 'Планы-графики реализации ГП',
  'gp.RealizationScheduleGPEvent': 'Мероприятия ГП в плане-графике реализации ГП',
  'assignments.Assignment': 'Поручения фонда капитального строительства и реконструкции',
  'assignments.AssignmentContent': 'Строки объектов капитального строительства',
  'gk.GK': 'Государственные контракты',
  'gk.AdditionalOKSGK': 'Дополнительные ОКС ГК',
  'gk.GKComment': 'Комментарии к государственным контрактам',
  'gk.LimitByYear': 'Лимиты финансирования по годам',
  'gk.QuarterLimit': 'Лимиты по кварталам',
  'gk.Builder': 'Подрядчики',
  'gk.DS': 'Дополнительные соглашения',
  'gk.PurchaseSchedule': 'План-графики закупок',
  'gk.PaymentDocs': 'Платежные документы исполнения',
  'gk.GKPrepaymentDoc': 'Платежные документы закрытия аванса',
  'gk.PaymentPlan': 'Планы платежей ГК',
  'gk.PaymentOrder': 'Платежные поручения',
  'gk.GKPrepayment': 'Авансы контрактов',
  'gk.ClosingDocument': 'Закрывающие документы',
  'gk.ProcurementPlanContent': 'Строки планов закупок',
  'gk.WorkType': 'Виды проводимых работ',
  'gk.BuilderSettingRating': 'Настройка для расчета рейтинга подрядной организации',
  'gk.AcceptedWork': 'Принимаемые работы',
  'gk.ProcurementPlanPurchase': 'Закупки планов закупок',
  'gk.AdditionalOKSProcurementPlanPurchase': 'Дополнительные ОКС для закупок ПЗ',
  'gk.PurchaseSchedulePurchase': 'Закупки плана-графика закупок',
  'gk.AdditionalOKSPurchaseSchedulePurchase': 'Дополнительные ОКС для закупок ПГЗ',
  'gk.GKRepayment': 'Погашения',
  'gk.PriceByYear': 'Стоимости по годам',
  'gk.GKSchedule': 'Календарные планы выполнения ГК',
  'gk.GKScheduleStage': 'Этапы календарных планов по ГК',
  'gk.GKScheduleContent': 'Строки календарного плана выполнение ГК',
  'gk.GKPrepaymentWork': 'Авансируемые работы',
  'gk.PaymentPlanSum': 'Суммы плана платежей ГК',
  'gk.GKRepaymentSchedule': 'Графики погашения',
  'gk.GKLot': 'Лоты госконтракта',
  'gk.OKVED': 'ОКВЭД',
  'gk.OKPD': 'ОКПД',
  'gk.Method': 'Способы закупки',
  'gk.TechnologicalConnectionType': 'Типы технологического присоединения',
  'gk.TechnologicalConnectionParam': 'Параметры технологического присоединения Договора',
  'gk.AIPEventPlanningPrice': 'Плановые стоимости мероприятий АИП',
  'gk.ProcurementPlan': 'Планы закупок',
  'gk.PurchaseScheduleContent': 'Строки плана-графика закупок',
  'gk.MeasurementUnit': 'Единицы измерения',
  'gk.GKTypeProvision': 'Виды обеспечений контрактов',
  'gk.GKProvision': 'Обеспечения контрактов',
  'gk.ReasonFailedProcedure': 'Причины несостоявшейся процедуры',
  'gk.ClosingDocumentType': 'Типы закрывающих документов',
  'docs.DocType': 'Типы документов',
  'docs.Doc': 'Прикрепленные Документы',
  'docs.OrganizationIssuedDoc': 'Организации, выдавшие документы',
  'settings.Settings': 'Параметры системы',
  'settings.VAT': 'НДС',
  'news.News': 'Новости',
  'uas.Address': 'Адреса',
  'uas.Prefix': 'Префиксы (текстовая часть адреса)',
  'uas.Building': 'Строения',
  'uas.Fias': 'Соответствия кодам ФИАС',
  'uas.Toponim': 'Топонимы',
  'uas.Area': 'Площадные объекты',
  'uas.AreaType': 'Типы площадных объектов',
  'uas.Geonim': 'Геонимы',
  'uas.GeonimType': 'Типы геонимов',
  'uas.Town': 'Города-поселки',
  'uas.Municipality': 'Муниципальные округа',
  'uas.SubRF': 'Субъекты РФ',
  'uas.District': 'Районы',
  'uas.Sources': 'Организации-источники',
  'uas.IdBuildingChanges': 'Перекодирование объектов',
  'support.TypeAppeal': 'Темы обращений',
  'support.Appeal': 'Обращения',
  'support.AppealInfoMessage': 'Информационное сообщение',
  'support.FAQ': 'Часто задаваемые вопросы',
  'support.TechnicalWork': 'Технические работы',
  'support.TechnicalWorkNotice': 'Отметки о просмотре служебных уведомлений',
  'notification.NotificationRecipients': 'Оповещения',
  'notification.NotificationEvent': 'Отложенные email-уведомления',
  'projects.Project': 'Проекты',
  'projects.ProjectPhase': 'Стадии проектов',
  'projects.ProjectStage': 'Этапы проектов',
  'projects.ProjectEvent': 'Мероприятия проектов',
  'projects.ProjectTaskType': 'Типы задач проектов',
  'projects.ProjectTask': 'Задачи проектов',
  'projects.RoadMapTemplateStage': 'Шаблоны - этапы проектов',
  'projects.RoadMapTemplateEvent': 'Шаблоны - мероприятия проектов',
  'projects.RoadMapTemplateTask': 'Шаблоны - задачи проектов',
  'projects.RoadMapTemplate': 'Шаблоны дорожной карты проекта',
  'projects.ProcessStage': 'Этапы регламентированного процесса',
  'projects.Process': 'Регламентированные процессы',
  'projects.ProjectTaskComment': 'Комментарии задач проектов',
  'projects.ProjectSettingRating': 'Настройка рейтинга проектов',
  'projects.CoordinationRoute': 'Маршруты согласования',
  'projects.ProjectType': 'Типы проектов',
  'projects.ProjectPhaseType': 'Типы стадий проекта',
  'projects.ProjectStageType': 'Типы этапов проекта',
  'projects.ProjectEventType': 'Типы мероприятий проекта',
  'projects.ProjectDelegation': 'Делегирования полномочий',
  'projects.ProgramType': 'Типы программ',
  'projects.Program': 'Программы проектов',
  'projects.BasePlanVersion': 'Версии базовых планов',
  'projects.TemplatePreviewTask': 'Предпросмотр задач',
  'projects.TemplatePreviewEvent': 'Предпросмотр мероприятий',
  'projects.TemplatePreviewStage': 'Предпросмотр этапов',
  'projects.TemplatePreviewPhase': 'Предпросмотр стадий',
  'projects.CoordinationRouteStep': 'Шаги согласования',
  'projects.FactualQuantity': 'Фактические количества',
  'projects.ProductionProgram': 'Производственные программы',
  'projects.ProductionProgramPlanValues': 'Плановые значения количества людей и техники',
  'claim_work.DocumentBase': 'Документы оснований начала претензионных работ',
  'claim_work.ClaimCase': 'Претензионные дела',
  'claim_work.CourtCase': 'Судебные дела',
  'claim_work.JudicialSitting': 'Судебные заседания',
  'claim_work.DemandType': 'Виды требований',
  'claim_work.Claim': 'Претензии',
  'claim_work.ClaimRecovery': 'Взыскания по претензиям',
  'claim_work.ClaimRecoveryPaymentDoc': 'Документы исполнения взысканий',
  'claim_work.Bank': 'Банки',
  'claim_work.Court': 'Суды',
  'claim_work.CourtCaseCategory': 'Категории судебных дел',
  'work_schedule.Work': 'Планируемые работы',
  'work_schedule.BlockWorks': 'Планируемые блоки работ',
  'work_schedule.WorkSchedule': 'Календарные план-графики',
  'aip_monitoring.Precept': 'Предписания об устранении выявленных нарушений',
  'aip_monitoring.ExpectedExecution': 'Ожидаемые выполнения',
  'aip_monitoring.Report': 'Отчеты инженеров по строительному контролю',
  'aip_monitoring.Departure': 'Выезды инженеров по строительному контролю',
  'aip_monitoring.DepartureSchedule': 'Графики выездов инженеров по строительному контролю',
  'aip_monitoring.DepartureResponsible': 'Ответственные за выезды',
  'aip_monitoring.DepartureWork': 'Работы к проверкам на даты выездов',
  'aip_monitoring.Objection': 'Возражения',
  'oks_planned_calculation.PlannedCalculation': 'Плановые расчеты стоимостей',
  'oks_planned_calculation.CalculationTechnologicalConnectionType': 'Типы технологического присоединения для расчета стоимости',
  'oks_planned_calculation.CalculationTechnologicalConnectionParam': 'Параметры технологического присоединения для расчета стоимости',
  'oks_planned_calculation.PlannedCalculationWorkTypePrice': 'Суммы плановых расчетов по видам работ',
  'oks_planned_calculation.PlannedCalculationTotalPrice': 'Итоговые суммы плановых расчетов',
  'oks_planned_calculation.PlannedCalculationVersion': 'Версии плановых расчетов стоимостей',
  'uds.ProjectDeclaration': 'Проектные декларации',
  'uds.DeveloperFounder': 'Учредители застройщика',
  'uds.MembershipSRO': 'Членства СРО',
  'uds.DeveloperProject': 'Проекты строительства',
  'uds.ResidentialComplex': 'Жилые комплексы',
  'uds.ZuTypeOwnership': 'Типы собственности на ЗУ',
  'uds.BuildingObject': 'Объекты застройки',
  'uds.BuildingTechnicalConnector': 'Технологические присоединения объектов застройки',
  'uds.ProjectImplementionSchedule': 'Графики реализации проекта',
  'uds.ShareAgreement': 'Договоры долевого участия',
  'essk.ChangedObjectSentLog': 'Логи отправки изменённых объектов',
  'essk.Job': 'Дела',
  'essk.Application': 'Информация о заявлениях',
  'essk.InterdepRequest': 'Межведомственные запросы',
  'essk.InterdepResponse': 'Межведомственные ответы',
  'essk.DocumentType': 'Типы документов',
  'essk.Document': 'Документы',
  'essk.Subject': 'Темы межведомственных запросов дел',
  'essk.Organization': 'Организации',
  'essk.Procedure': 'Процедуры',
  'essk.ChangedObjects': 'Изменённые объекты',
  'uds_report.QuarterlyReportType': 'Типы ежеквартальных отчетов',
  'uds_report.QuarterlyReportingPackage': 'Пакеты ежеквартальных отчетностей',
  'uds_report.QuarterlyReport': 'Ежеквартальные отчеты',
  'uds_report.AnnualReportType': 'Типы годовых отчетов',
  'uds_report.AnnualReportingPackage': 'Пакеты годовых отчетностей',
  'uds_report.AnnualReport': 'Годовые отчеты',
  'uds_report.AuditReport': 'Аудиторские заключения',
  'uds_report.DDUSignedCast': 'Подписанные слепки ДДУ',
  'uds_report.CautionReport': 'Предостережения',
  'uds_report.Objection': 'Возражения',
  'uds_report.AuditPlan': 'Планы проверок',
  'uds_report.AuditPlanEvent': 'Мероприятия планов проверок',
  'media_inquiry.Inquiry': 'Запросы СМИ',
  'reports.ManualReport': 'Ручные отчеты',
  'rating.Rating': 'Рейтинги',
  'financial_management.CashPlan': 'Кассовые планы',
  'financial_management.BudgetPaymentDoc': 'Платежные документы из бюджета',
  'financial_management.PlannedDevelopment': 'Планируемые освоения',
  'financial_management.PaymentDistribution': 'Распределения платежей',
  'gorod.Problem': 'Обращения граждан',
  'gorod.ProblemHistory': 'История обращения',
  'gorod.ProblemDoc': 'Документы обращения',
  'system_security.Backup': 'Бэкапы',
  'system_security.SecurityLog': 'Журналирование событий безопасности',
  'version_control.ModelObjectVersion': 'Версии объектов',
  'version_control.ModelObjectVersionGroup': 'Группы версий объектов',
  'system_security.HistoryRecord': 'Записи изменений',
  'system_security.ModelObjectHistory': 'Истории изменений объектов',
  'sign_manager.SignManagerSignature': 'Подписи объектов',
  'aisbp.AISBPRequest': 'Запросы в АИС БП, ожидающие получения данных',
  'aisbp.AISBPRequestLog': 'Логи запроса в АИС БП',
  'eis.EISLastUpdate': 'История обновления данных из ЕИС',
  'eis.EISWrongFiles': 'Нечитаемые файлы',
  'eis.OKPDProxy': 'ОКПД',
  'eis.OKVEDProxy': 'ОКВЭД',
  'eis.MethodProxy': 'Способы закупки',
  'eis.ReasonFailedProcedureProxy': 'Причины несостоявшейся процедуры',
  'eis.MeasurementUnitProxy': 'Единицы измерения'
}